-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN (   
        SELECT B.ITEM_ID, B.PARENT_ITEM_ID, A.RARITY
        FROM ITEM_INFO AS A
        JOIN ITEM_TREE AS B
        ON A.ITEM_ID = B.PARENT_ITEM_ID
        WHERE RARITY = 'RARE'
    ) AS R
ON I.ITEM_ID = R.ITEM_ID
ORDER BY R.ITEM_ID DESC;