-- 코드를 작성해주세요
SELECT DISTINCT(A.ID), A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS AS A
JOIN SKILLCODES AS B
ON A.SKILL_CODE & B.CODE = B.CODE
WHERE B.NAME = 'Python' OR B.NAME = 'C#'
ORDER BY A.ID ASC;